package com.rbac.console.dao;

import com.rbac.console.entity.ConsoleRoleMenu;
import com.rbac.console.entity.ConsoleRoleMenuExample;
import org.apache.ibatis.annotations.Mapper;

import java.util.List;
@Mapper
public interface ConsoleRoleMenuMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table _CONSOLE_ROLE_MENU
     *
     * @mbggenerated
     */
    int countByExample(ConsoleRoleMenuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table _CONSOLE_ROLE_MENU
     *
     * @mbggenerated
     */
    int deleteByExample(ConsoleRoleMenuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table _CONSOLE_ROLE_MENU
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table _CONSOLE_ROLE_MENU
     *
     * @mbggenerated
     */
    int insert(ConsoleRoleMenu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table _CONSOLE_ROLE_MENU
     *
     * @mbggenerated
     */
    int insertSelective(ConsoleRoleMenu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table _CONSOLE_ROLE_MENU
     *
     * @mbggenerated
     */
    List<ConsoleRoleMenu> selectByExample(ConsoleRoleMenuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table _CONSOLE_ROLE_MENU
     *
     * @mbggenerated
     */
    ConsoleRoleMenu selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table _CONSOLE_ROLE_MENU
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(ConsoleRoleMenu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table _CONSOLE_ROLE_MENU
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(ConsoleRoleMenu record);
}