package com.rbac.console.dao;

import com.rbac.console.entity.ConsoleUser;
import com.rbac.console.entity.ConsoleUserExample;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

import java.util.List;
import java.util.Map;

@Mapper
public interface ConsoleUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table _CONSOLE_USER
     *
     * @mbggenerated
     */
    int countByExample(ConsoleUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table _CONSOLE_USER
     *
     * @mbggenerated
     */
    int deleteByExample(ConsoleUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table _CONSOLE_USER
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table _CONSOLE_USER
     *
     * @mbggenerated
     */
    int insert(ConsoleUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table _CONSOLE_USER
     *
     * @mbggenerated
     */
    int insertSelective(ConsoleUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table _CONSOLE_USER
     *
     * @mbggenerated
     */
    List<ConsoleUser> selectByExample(ConsoleUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table _CONSOLE_USER
     *
     * @mbggenerated
     */
    ConsoleUser selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table _CONSOLE_USER
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") ConsoleUser record, @Param("example") ConsoleUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table _CONSOLE_USER
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") ConsoleUser record, @Param("example") ConsoleUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table _CONSOLE_USER
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(ConsoleUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table _CONSOLE_USER
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(ConsoleUser record);
    public List<ConsoleUser> selectConsoleUser(Map<String, Object> params);
}