package com.rbac.console.entity;

import java.util.Date;

public class ConsoleRole {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CONSOLE_ROLE.ID
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CONSOLE_ROLE.ROLENAME
     *
     * @mbggenerated
     */
    private String rolename;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CONSOLE_ROLE.ROLE_CODE
     *
     * @mbggenerated
     */
    private String roleCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CONSOLE_ROLE.IS_DELETE
     *
     * @mbggenerated
     */
    private String isDelete;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CONSOLE_ROLE.ROLEDESC
     *
     * @mbggenerated
     */
    private String roledesc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CONSOLE_ROLE.CREATE_TIME
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CONSOLE_ROLE.CREATE_USERID
     *
     * @mbggenerated
     */
    private Integer createUserid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CONSOLE_ROLE.CREATE_USERNAME
     *
     * @mbggenerated
     */
    private String createUsername;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CONSOLE_ROLE.ID
     *
     * @return the value of CONSOLE_ROLE.ID
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CONSOLE_ROLE.ID
     *
     * @param id the value for CONSOLE_ROLE.ID
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CONSOLE_ROLE.ROLENAME
     *
     * @return the value of CONSOLE_ROLE.ROLENAME
     *
     * @mbggenerated
     */
    public String getRolename() {
        return rolename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CONSOLE_ROLE.ROLENAME
     *
     * @param rolename the value for CONSOLE_ROLE.ROLENAME
     *
     * @mbggenerated
     */
    public void setRolename(String rolename) {
        this.rolename = rolename == null ? null : rolename.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CONSOLE_ROLE.ROLE_CODE
     *
     * @return the value of CONSOLE_ROLE.ROLE_CODE
     *
     * @mbggenerated
     */
    public String getRoleCode() {
        return roleCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CONSOLE_ROLE.ROLE_CODE
     *
     * @param roleCode the value for CONSOLE_ROLE.ROLE_CODE
     *
     * @mbggenerated
     */
    public void setRoleCode(String roleCode) {
        this.roleCode = roleCode == null ? null : roleCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CONSOLE_ROLE.IS_DELETE
     *
     * @return the value of CONSOLE_ROLE.IS_DELETE
     *
     * @mbggenerated
     */
    public String getIsDelete() {
        return isDelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CONSOLE_ROLE.IS_DELETE
     *
     * @param isDelete the value for CONSOLE_ROLE.IS_DELETE
     *
     * @mbggenerated
     */
    public void setIsDelete(String isDelete) {
        this.isDelete = isDelete == null ? null : isDelete.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CONSOLE_ROLE.ROLEDESC
     *
     * @return the value of CONSOLE_ROLE.ROLEDESC
     *
     * @mbggenerated
     */
    public String getRoledesc() {
        return roledesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CONSOLE_ROLE.ROLEDESC
     *
     * @param roledesc the value for CONSOLE_ROLE.ROLEDESC
     *
     * @mbggenerated
     */
    public void setRoledesc(String roledesc) {
        this.roledesc = roledesc == null ? null : roledesc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CONSOLE_ROLE.CREATE_TIME
     *
     * @return the value of CONSOLE_ROLE.CREATE_TIME
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CONSOLE_ROLE.CREATE_TIME
     *
     * @param createTime the value for CONSOLE_ROLE.CREATE_TIME
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CONSOLE_ROLE.CREATE_USERID
     *
     * @return the value of CONSOLE_ROLE.CREATE_USERID
     *
     * @mbggenerated
     */
    public Integer getCreateUserid() {
        return createUserid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CONSOLE_ROLE.CREATE_USERID
     *
     * @param createUserid the value for CONSOLE_ROLE.CREATE_USERID
     *
     * @mbggenerated
     */
    public void setCreateUserid(Integer createUserid) {
        this.createUserid = createUserid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CONSOLE_ROLE.CREATE_USERNAME
     *
     * @return the value of CONSOLE_ROLE.CREATE_USERNAME
     *
     * @mbggenerated
     */
    public String getCreateUsername() {
        return createUsername;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CONSOLE_ROLE.CREATE_USERNAME
     *
     * @param createUsername the value for CONSOLE_ROLE.CREATE_USERNAME
     *
     * @mbggenerated
     */
    public void setCreateUsername(String createUsername) {
        this.createUsername = createUsername == null ? null : createUsername.trim();
    }
}