package com.rbac.console.entity;

import java.io.Serializable;

public class ConsoleMenu implements Serializable{
    /**
	 * 
	 */
	private static final long serialVersionUID = -425479915619109199L;

	/**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CONSOLE_MENU.ID
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CONSOLE_MENU.MENU_NAME
     *
     * @mbggenerated
     */
    private String menuName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CONSOLE_MENU.MENU_DESC
     *
     * @mbggenerated
     */
    private String menuDesc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CONSOLE_MENU.PARENT_ID
     *
     * @mbggenerated
     */
    private Integer parentId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CONSOLE_MENU.MENU_CODE
     *
     * @mbggenerated
     */
    private String menuCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CONSOLE_MENU.MENU_HREF
     *
     * @mbggenerated
     */
    private String menuHref;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CONSOLE_MENU.ISADMIN_MENU
     *
     * @mbggenerated
     */
    private String isadminMenu;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CONSOLE_MENU.IS_DELETE
     *
     * @mbggenerated
     */
    private String isDelete;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CONSOLE_MENU.ISCAN_UPDATE
     *
     * @mbggenerated
     */
    private String iscanUpdate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CONSOLE_MENU.MENU_LEVEL
     *
     * @mbggenerated
     */
    private String menuLevel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CONSOLE_MENU.BUTTON_HTMLCONTENT
     *
     * @mbggenerated
     */
    private String buttonHtmlcontent;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CONSOLE_MENU.ISMENU
     *
     * @mbggenerated
     */
    private String ismenu;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CONSOLE_MENU.MENU_PARM1
     *
     * @mbggenerated
     */
    private Integer menuParm1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CONSOLE_MENU.MENU_PARM2
     *
     * @mbggenerated
     */
    private Integer menuParm2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CONSOLE_MENU.MENU_PARM3
     *
     * @mbggenerated
     */
    private String menuParm3;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CONSOLE_MENU.MENU_PARM4
     *
     * @mbggenerated
     */
    private String menuParm4;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CONSOLE_MENU.ID
     *
     * @return the value of CONSOLE_MENU.ID
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CONSOLE_MENU.ID
     *
     * @param id the value for CONSOLE_MENU.ID
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CONSOLE_MENU.MENU_NAME
     *
     * @return the value of CONSOLE_MENU.MENU_NAME
     *
     * @mbggenerated
     */
    public String getMenuName() {
        return menuName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CONSOLE_MENU.MENU_NAME
     *
     * @param menuName the value for CONSOLE_MENU.MENU_NAME
     *
     * @mbggenerated
     */
    public void setMenuName(String menuName) {
        this.menuName = menuName == null ? null : menuName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CONSOLE_MENU.MENU_DESC
     *
     * @return the value of CONSOLE_MENU.MENU_DESC
     *
     * @mbggenerated
     */
    public String getMenuDesc() {
        return menuDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CONSOLE_MENU.MENU_DESC
     *
     * @param menuDesc the value for CONSOLE_MENU.MENU_DESC
     *
     * @mbggenerated
     */
    public void setMenuDesc(String menuDesc) {
        this.menuDesc = menuDesc == null ? null : menuDesc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CONSOLE_MENU.PARENT_ID
     *
     * @return the value of CONSOLE_MENU.PARENT_ID
     *
     * @mbggenerated
     */
    public Integer getParentId() {
        return parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CONSOLE_MENU.PARENT_ID
     *
     * @param parentId the value for CONSOLE_MENU.PARENT_ID
     *
     * @mbggenerated
     */
    public void setParentId(Integer parentId) {
        this.parentId = parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CONSOLE_MENU.MENU_CODE
     *
     * @return the value of CONSOLE_MENU.MENU_CODE
     *
     * @mbggenerated
     */
    public String getMenuCode() {
        return menuCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CONSOLE_MENU.MENU_CODE
     *
     * @param menuCode the value for CONSOLE_MENU.MENU_CODE
     *
     * @mbggenerated
     */
    public void setMenuCode(String menuCode) {
        this.menuCode = menuCode == null ? null : menuCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CONSOLE_MENU.MENU_HREF
     *
     * @return the value of CONSOLE_MENU.MENU_HREF
     *
     * @mbggenerated
     */
    public String getMenuHref() {
        return menuHref;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CONSOLE_MENU.MENU_HREF
     *
     * @param menuHref the value for CONSOLE_MENU.MENU_HREF
     *
     * @mbggenerated
     */
    public void setMenuHref(String menuHref) {
        this.menuHref = menuHref == null ? null : menuHref.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CONSOLE_MENU.ISADMIN_MENU
     *
     * @return the value of CONSOLE_MENU.ISADMIN_MENU
     *
     * @mbggenerated
     */
    public String getIsadminMenu() {
        return isadminMenu;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CONSOLE_MENU.ISADMIN_MENU
     *
     * @param isadminMenu the value for CONSOLE_MENU.ISADMIN_MENU
     *
     * @mbggenerated
     */
    public void setIsadminMenu(String isadminMenu) {
        this.isadminMenu = isadminMenu == null ? null : isadminMenu.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CONSOLE_MENU.IS_DELETE
     *
     * @return the value of CONSOLE_MENU.IS_DELETE
     *
     * @mbggenerated
     */
    public String getIsDelete() {
        return isDelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CONSOLE_MENU.IS_DELETE
     *
     * @param isDelete the value for CONSOLE_MENU.IS_DELETE
     *
     * @mbggenerated
     */
    public void setIsDelete(String isDelete) {
        this.isDelete = isDelete == null ? null : isDelete.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CONSOLE_MENU.ISCAN_UPDATE
     *
     * @return the value of CONSOLE_MENU.ISCAN_UPDATE
     *
     * @mbggenerated
     */
    public String getIscanUpdate() {
        return iscanUpdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CONSOLE_MENU.ISCAN_UPDATE
     *
     * @param iscanUpdate the value for CONSOLE_MENU.ISCAN_UPDATE
     *
     * @mbggenerated
     */
    public void setIscanUpdate(String iscanUpdate) {
        this.iscanUpdate = iscanUpdate == null ? null : iscanUpdate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CONSOLE_MENU.MENU_LEVEL
     *
     * @return the value of CONSOLE_MENU.MENU_LEVEL
     *
     * @mbggenerated
     */
    public String getMenuLevel() {
        return menuLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CONSOLE_MENU.MENU_LEVEL
     *
     * @param menuLevel the value for CONSOLE_MENU.MENU_LEVEL
     *
     * @mbggenerated
     */
    public void setMenuLevel(String menuLevel) {
        this.menuLevel = menuLevel == null ? null : menuLevel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CONSOLE_MENU.BUTTON_HTMLCONTENT
     *
     * @return the value of CONSOLE_MENU.BUTTON_HTMLCONTENT
     *
     * @mbggenerated
     */
    public String getButtonHtmlcontent() {
        return buttonHtmlcontent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CONSOLE_MENU.BUTTON_HTMLCONTENT
     *
     * @param buttonHtmlcontent the value for CONSOLE_MENU.BUTTON_HTMLCONTENT
     *
     * @mbggenerated
     */
    public void setButtonHtmlcontent(String buttonHtmlcontent) {
        this.buttonHtmlcontent = buttonHtmlcontent == null ? null : buttonHtmlcontent.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CONSOLE_MENU.ISMENU
     *
     * @return the value of CONSOLE_MENU.ISMENU
     *
     * @mbggenerated
     */
    public String getIsmenu() {
        return ismenu;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CONSOLE_MENU.ISMENU
     *
     * @param ismenu the value for CONSOLE_MENU.ISMENU
     *
     * @mbggenerated
     */
    public void setIsmenu(String ismenu) {
        this.ismenu = ismenu == null ? null : ismenu.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CONSOLE_MENU.MENU_PARM1
     *
     * @return the value of CONSOLE_MENU.MENU_PARM1
     *
     * @mbggenerated
     */
    public Integer getMenuParm1() {
        return menuParm1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CONSOLE_MENU.MENU_PARM1
     *
     * @param menuParm1 the value for CONSOLE_MENU.MENU_PARM1
     *
     * @mbggenerated
     */
    public void setMenuParm1(Integer menuParm1) {
        this.menuParm1 = menuParm1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CONSOLE_MENU.MENU_PARM2
     *
     * @return the value of CONSOLE_MENU.MENU_PARM2
     *
     * @mbggenerated
     */
    public Integer getMenuParm2() {
        return menuParm2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CONSOLE_MENU.MENU_PARM2
     *
     * @param menuParm2 the value for CONSOLE_MENU.MENU_PARM2
     *
     * @mbggenerated
     */
    public void setMenuParm2(Integer menuParm2) {
        this.menuParm2 = menuParm2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CONSOLE_MENU.MENU_PARM3
     *
     * @return the value of CONSOLE_MENU.MENU_PARM3
     *
     * @mbggenerated
     */
    public String getMenuParm3() {
        return menuParm3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CONSOLE_MENU.MENU_PARM3
     *
     * @param menuParm3 the value for CONSOLE_MENU.MENU_PARM3
     *
     * @mbggenerated
     */
    public void setMenuParm3(String menuParm3) {
        this.menuParm3 = menuParm3 == null ? null : menuParm3.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CONSOLE_MENU.MENU_PARM4
     *
     * @return the value of CONSOLE_MENU.MENU_PARM4
     *
     * @mbggenerated
     */
    public String getMenuParm4() {
        return menuParm4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CONSOLE_MENU.MENU_PARM4
     *
     * @param menuParm4 the value for CONSOLE_MENU.MENU_PARM4
     *
     * @mbggenerated
     */
    public void setMenuParm4(String menuParm4) {
        this.menuParm4 = menuParm4 == null ? null : menuParm4.trim();
    }
}