package com.rbac.console.entity;

import java.util.Date;

public class ConsoleUserRole {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CONSOLE_USER_ROLE.ID
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CONSOLE_USER_ROLE.USER_ID
     *
     * @mbggenerated
     */
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CONSOLE_USER_ROLE.ROLE_ID
     *
     * @mbggenerated
     */
    private Integer roleId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CONSOLE_USER_ROLE.ROLE_NAME
     *
     * @mbggenerated
     */
    private String roleName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CONSOLE_USER_ROLE.STATUS
     *
     * @mbggenerated
     */
    private Integer status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CONSOLE_USER_ROLE.CREATE_USERID
     *
     * @mbggenerated
     */
    private Integer createUserid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CONSOLE_USER_ROLE.CREATE_TIME
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CONSOLE_USER_ROLE.PARM1
     *
     * @mbggenerated
     */
    private Integer parm1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CONSOLE_USER_ROLE.PARM2
     *
     * @mbggenerated
     */
    private String parm2;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CONSOLE_USER_ROLE.ID
     *
     * @return the value of CONSOLE_USER_ROLE.ID
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CONSOLE_USER_ROLE.ID
     *
     * @param id the value for CONSOLE_USER_ROLE.ID
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CONSOLE_USER_ROLE.USER_ID
     *
     * @return the value of CONSOLE_USER_ROLE.USER_ID
     *
     * @mbggenerated
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CONSOLE_USER_ROLE.USER_ID
     *
     * @param userId the value for CONSOLE_USER_ROLE.USER_ID
     *
     * @mbggenerated
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CONSOLE_USER_ROLE.ROLE_ID
     *
     * @return the value of CONSOLE_USER_ROLE.ROLE_ID
     *
     * @mbggenerated
     */
    public Integer getRoleId() {
        return roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CONSOLE_USER_ROLE.ROLE_ID
     *
     * @param roleId the value for CONSOLE_USER_ROLE.ROLE_ID
     *
     * @mbggenerated
     */
    public void setRoleId(Integer roleId) {
        this.roleId = roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CONSOLE_USER_ROLE.ROLE_NAME
     *
     * @return the value of CONSOLE_USER_ROLE.ROLE_NAME
     *
     * @mbggenerated
     */
    public String getRoleName() {
        return roleName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CONSOLE_USER_ROLE.ROLE_NAME
     *
     * @param roleName the value for CONSOLE_USER_ROLE.ROLE_NAME
     *
     * @mbggenerated
     */
    public void setRoleName(String roleName) {
        this.roleName = roleName == null ? null : roleName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CONSOLE_USER_ROLE.STATUS
     *
     * @return the value of CONSOLE_USER_ROLE.STATUS
     *
     * @mbggenerated
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CONSOLE_USER_ROLE.STATUS
     *
     * @param status the value for CONSOLE_USER_ROLE.STATUS
     *
     * @mbggenerated
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CONSOLE_USER_ROLE.CREATE_USERID
     *
     * @return the value of CONSOLE_USER_ROLE.CREATE_USERID
     *
     * @mbggenerated
     */
    public Integer getCreateUserid() {
        return createUserid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CONSOLE_USER_ROLE.CREATE_USERID
     *
     * @param createUserid the value for CONSOLE_USER_ROLE.CREATE_USERID
     *
     * @mbggenerated
     */
    public void setCreateUserid(Integer createUserid) {
        this.createUserid = createUserid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CONSOLE_USER_ROLE.CREATE_TIME
     *
     * @return the value of CONSOLE_USER_ROLE.CREATE_TIME
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CONSOLE_USER_ROLE.CREATE_TIME
     *
     * @param createTime the value for CONSOLE_USER_ROLE.CREATE_TIME
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CONSOLE_USER_ROLE.PARM1
     *
     * @return the value of CONSOLE_USER_ROLE.PARM1
     *
     * @mbggenerated
     */
    public Integer getParm1() {
        return parm1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CONSOLE_USER_ROLE.PARM1
     *
     * @param parm1 the value for CONSOLE_USER_ROLE.PARM1
     *
     * @mbggenerated
     */
    public void setParm1(Integer parm1) {
        this.parm1 = parm1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CONSOLE_USER_ROLE.PARM2
     *
     * @return the value of CONSOLE_USER_ROLE.PARM2
     *
     * @mbggenerated
     */
    public String getParm2() {
        return parm2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CONSOLE_USER_ROLE.PARM2
     *
     * @param parm2 the value for CONSOLE_USER_ROLE.PARM2
     *
     * @mbggenerated
     */
    public void setParm2(String parm2) {
        this.parm2 = parm2 == null ? null : parm2.trim();
    }
}