package com.rbac.console.entity;

import java.io.Serializable;
import java.util.Date;

public class ConsoleUser implements Serializable{
    /**
	 * 
	 */
	private static final long serialVersionUID = 699600714555208636L;

	/**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CONSOLE_USER.ID
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CONSOLE_USER.USERNAME
     *
     * @mbggenerated
     */
    private String username;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CONSOLE_USER.PASSWORD
     *
     * @mbggenerated
     */
    private String password;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CONSOLE_USER.TRUENAME
     *
     * @mbggenerated
     */
    private String truename;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CONSOLE_USER.USER_SEX
     *
     * @mbggenerated
     */
    private String userSex;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CONSOLE_USER.USER_BIRTHDAY
     *
     * @mbggenerated
     */
    private Date userBirthday;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CONSOLE_USER.USER_EMAIL
     *
     * @mbggenerated
     */
    private String userEmail;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CONSOLE_USER.USER_CREATTIME
     *
     * @mbggenerated
     */
    private Date userCreattime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CONSOLE_USER.USER_STATUS
     *
     * @mbggenerated
     */
    private Integer userStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CONSOLE_USER.TELEPHONE
     *
     * @mbggenerated
     */
    private String telephone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CONSOLE_USER.MOBILE
     *
     * @mbggenerated
     */
    private String mobile;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CONSOLE_USER.DEPARTMENT
     *
     * @mbggenerated
     */
    private String department;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CONSOLE_USER.USER_PARM1
     *
     * @mbggenerated
     */
    private Integer userParm1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CONSOLE_USER.USER_PARM2
     *
     * @mbggenerated
     */
    private String userParm2;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CONSOLE_USER.ID
     *
     * @return the value of CONSOLE_USER.ID
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CONSOLE_USER.ID
     *
     * @param id the value for CONSOLE_USER.ID
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CONSOLE_USER.USERNAME
     *
     * @return the value of CONSOLE_USER.USERNAME
     *
     * @mbggenerated
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CONSOLE_USER.USERNAME
     *
     * @param username the value for CONSOLE_USER.USERNAME
     *
     * @mbggenerated
     */
    public void setUsername(String username) {
        this.username = username == null ? null : username.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CONSOLE_USER.PASSWORD
     *
     * @return the value of CONSOLE_USER.PASSWORD
     *
     * @mbggenerated
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CONSOLE_USER.PASSWORD
     *
     * @param password the value for CONSOLE_USER.PASSWORD
     *
     * @mbggenerated
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CONSOLE_USER.TRUENAME
     *
     * @return the value of CONSOLE_USER.TRUENAME
     *
     * @mbggenerated
     */
    public String getTruename() {
        return truename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CONSOLE_USER.TRUENAME
     *
     * @param truename the value for CONSOLE_USER.TRUENAME
     *
     * @mbggenerated
     */
    public void setTruename(String truename) {
        this.truename = truename == null ? null : truename.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CONSOLE_USER.USER_SEX
     *
     * @return the value of CONSOLE_USER.USER_SEX
     *
     * @mbggenerated
     */
    public String getUserSex() {
        return userSex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CONSOLE_USER.USER_SEX
     *
     * @param userSex the value for CONSOLE_USER.USER_SEX
     *
     * @mbggenerated
     */
    public void setUserSex(String userSex) {
        this.userSex = userSex == null ? null : userSex.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CONSOLE_USER.USER_BIRTHDAY
     *
     * @return the value of CONSOLE_USER.USER_BIRTHDAY
     *
     * @mbggenerated
     */
    public Date getUserBirthday() {
        return userBirthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CONSOLE_USER.USER_BIRTHDAY
     *
     * @param userBirthday the value for CONSOLE_USER.USER_BIRTHDAY
     *
     * @mbggenerated
     */
    public void setUserBirthday(Date userBirthday) {
        this.userBirthday = userBirthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CONSOLE_USER.USER_EMAIL
     *
     * @return the value of CONSOLE_USER.USER_EMAIL
     *
     * @mbggenerated
     */
    public String getUserEmail() {
        return userEmail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CONSOLE_USER.USER_EMAIL
     *
     * @param userEmail the value for CONSOLE_USER.USER_EMAIL
     *
     * @mbggenerated
     */
    public void setUserEmail(String userEmail) {
        this.userEmail = userEmail == null ? null : userEmail.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CONSOLE_USER.USER_CREATTIME
     *
     * @return the value of CONSOLE_USER.USER_CREATTIME
     *
     * @mbggenerated
     */
    public Date getUserCreattime() {
        return userCreattime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CONSOLE_USER.USER_CREATTIME
     *
     * @param userCreattime the value for CONSOLE_USER.USER_CREATTIME
     *
     * @mbggenerated
     */
    public void setUserCreattime(Date userCreattime) {
        this.userCreattime = userCreattime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CONSOLE_USER.USER_STATUS
     *
     * @return the value of CONSOLE_USER.USER_STATUS
     *
     * @mbggenerated
     */
    public Integer getUserStatus() {
        return userStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CONSOLE_USER.USER_STATUS
     *
     * @param userStatus the value for CONSOLE_USER.USER_STATUS
     *
     * @mbggenerated
     */
    public void setUserStatus(Integer userStatus) {
        this.userStatus = userStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CONSOLE_USER.TELEPHONE
     *
     * @return the value of CONSOLE_USER.TELEPHONE
     *
     * @mbggenerated
     */
    public String getTelephone() {
        return telephone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CONSOLE_USER.TELEPHONE
     *
     * @param telephone the value for CONSOLE_USER.TELEPHONE
     *
     * @mbggenerated
     */
    public void setTelephone(String telephone) {
        this.telephone = telephone == null ? null : telephone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CONSOLE_USER.MOBILE
     *
     * @return the value of CONSOLE_USER.MOBILE
     *
     * @mbggenerated
     */
    public String getMobile() {
        return mobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CONSOLE_USER.MOBILE
     *
     * @param mobile the value for CONSOLE_USER.MOBILE
     *
     * @mbggenerated
     */
    public void setMobile(String mobile) {
        this.mobile = mobile == null ? null : mobile.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CONSOLE_USER.DEPARTMENT
     *
     * @return the value of CONSOLE_USER.DEPARTMENT
     *
     * @mbggenerated
     */
    public String getDepartment() {
        return department;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CONSOLE_USER.DEPARTMENT
     *
     * @param department the value for CONSOLE_USER.DEPARTMENT
     *
     * @mbggenerated
     */
    public void setDepartment(String department) {
        this.department = department == null ? null : department.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CONSOLE_USER.USER_PARM1
     *
     * @return the value of CONSOLE_USER.USER_PARM1
     *
     * @mbggenerated
     */
    public Integer getUserParm1() {
        return userParm1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CONSOLE_USER.USER_PARM1
     *
     * @param userParm1 the value for CONSOLE_USER.USER_PARM1
     *
     * @mbggenerated
     */
    public void setUserParm1(Integer userParm1) {
        this.userParm1 = userParm1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CONSOLE_USER.USER_PARM2
     *
     * @return the value of CONSOLE_USER.USER_PARM2
     *
     * @mbggenerated
     */
    public String getUserParm2() {
        return userParm2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CONSOLE_USER.USER_PARM2
     *
     * @param userParm2 the value for CONSOLE_USER.USER_PARM2
     *
     * @mbggenerated
     */
    public void setUserParm2(String userParm2) {
        this.userParm2 = userParm2 == null ? null : userParm2.trim();
    }
}