package com.rbac.console.entity;

import java.util.ArrayList;
import java.util.List;

public class ConsoleMenuExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table CONSOLE_MENU
     *
     * @mbggenerated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table CONSOLE_MENU
     *
     * @mbggenerated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table CONSOLE_MENU
     *
     * @mbggenerated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CONSOLE_MENU
     *
     * @mbggenerated
     */
    public ConsoleMenuExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CONSOLE_MENU
     *
     * @mbggenerated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CONSOLE_MENU
     *
     * @mbggenerated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CONSOLE_MENU
     *
     * @mbggenerated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CONSOLE_MENU
     *
     * @mbggenerated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CONSOLE_MENU
     *
     * @mbggenerated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CONSOLE_MENU
     *
     * @mbggenerated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CONSOLE_MENU
     *
     * @mbggenerated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CONSOLE_MENU
     *
     * @mbggenerated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CONSOLE_MENU
     *
     * @mbggenerated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CONSOLE_MENU
     *
     * @mbggenerated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table CONSOLE_MENU
     *
     * @mbggenerated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("ID is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("ID is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("ID =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("ID <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("ID >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("ID >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("ID <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("ID <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("ID in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("ID not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("ID between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("ID not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andMenuNameIsNull() {
            addCriterion("MENU_NAME is null");
            return (Criteria) this;
        }

        public Criteria andMenuNameIsNotNull() {
            addCriterion("MENU_NAME is not null");
            return (Criteria) this;
        }

        public Criteria andMenuNameEqualTo(String value) {
            addCriterion("MENU_NAME =", value, "menuName");
            return (Criteria) this;
        }

        public Criteria andMenuNameNotEqualTo(String value) {
            addCriterion("MENU_NAME <>", value, "menuName");
            return (Criteria) this;
        }

        public Criteria andMenuNameGreaterThan(String value) {
            addCriterion("MENU_NAME >", value, "menuName");
            return (Criteria) this;
        }

        public Criteria andMenuNameGreaterThanOrEqualTo(String value) {
            addCriterion("MENU_NAME >=", value, "menuName");
            return (Criteria) this;
        }

        public Criteria andMenuNameLessThan(String value) {
            addCriterion("MENU_NAME <", value, "menuName");
            return (Criteria) this;
        }

        public Criteria andMenuNameLessThanOrEqualTo(String value) {
            addCriterion("MENU_NAME <=", value, "menuName");
            return (Criteria) this;
        }

        public Criteria andMenuNameLike(String value) {
            addCriterion("MENU_NAME like", value, "menuName");
            return (Criteria) this;
        }

        public Criteria andMenuNameNotLike(String value) {
            addCriterion("MENU_NAME not like", value, "menuName");
            return (Criteria) this;
        }

        public Criteria andMenuNameIn(List<String> values) {
            addCriterion("MENU_NAME in", values, "menuName");
            return (Criteria) this;
        }

        public Criteria andMenuNameNotIn(List<String> values) {
            addCriterion("MENU_NAME not in", values, "menuName");
            return (Criteria) this;
        }

        public Criteria andMenuNameBetween(String value1, String value2) {
            addCriterion("MENU_NAME between", value1, value2, "menuName");
            return (Criteria) this;
        }

        public Criteria andMenuNameNotBetween(String value1, String value2) {
            addCriterion("MENU_NAME not between", value1, value2, "menuName");
            return (Criteria) this;
        }

        public Criteria andMenuDescIsNull() {
            addCriterion("MENU_DESC is null");
            return (Criteria) this;
        }

        public Criteria andMenuDescIsNotNull() {
            addCriterion("MENU_DESC is not null");
            return (Criteria) this;
        }

        public Criteria andMenuDescEqualTo(String value) {
            addCriterion("MENU_DESC =", value, "menuDesc");
            return (Criteria) this;
        }

        public Criteria andMenuDescNotEqualTo(String value) {
            addCriterion("MENU_DESC <>", value, "menuDesc");
            return (Criteria) this;
        }

        public Criteria andMenuDescGreaterThan(String value) {
            addCriterion("MENU_DESC >", value, "menuDesc");
            return (Criteria) this;
        }

        public Criteria andMenuDescGreaterThanOrEqualTo(String value) {
            addCriterion("MENU_DESC >=", value, "menuDesc");
            return (Criteria) this;
        }

        public Criteria andMenuDescLessThan(String value) {
            addCriterion("MENU_DESC <", value, "menuDesc");
            return (Criteria) this;
        }

        public Criteria andMenuDescLessThanOrEqualTo(String value) {
            addCriterion("MENU_DESC <=", value, "menuDesc");
            return (Criteria) this;
        }

        public Criteria andMenuDescLike(String value) {
            addCriterion("MENU_DESC like", value, "menuDesc");
            return (Criteria) this;
        }

        public Criteria andMenuDescNotLike(String value) {
            addCriterion("MENU_DESC not like", value, "menuDesc");
            return (Criteria) this;
        }

        public Criteria andMenuDescIn(List<String> values) {
            addCriterion("MENU_DESC in", values, "menuDesc");
            return (Criteria) this;
        }

        public Criteria andMenuDescNotIn(List<String> values) {
            addCriterion("MENU_DESC not in", values, "menuDesc");
            return (Criteria) this;
        }

        public Criteria andMenuDescBetween(String value1, String value2) {
            addCriterion("MENU_DESC between", value1, value2, "menuDesc");
            return (Criteria) this;
        }

        public Criteria andMenuDescNotBetween(String value1, String value2) {
            addCriterion("MENU_DESC not between", value1, value2, "menuDesc");
            return (Criteria) this;
        }

        public Criteria andParentIdIsNull() {
            addCriterion("PARENT_ID is null");
            return (Criteria) this;
        }

        public Criteria andParentIdIsNotNull() {
            addCriterion("PARENT_ID is not null");
            return (Criteria) this;
        }

        public Criteria andParentIdEqualTo(Integer value) {
            addCriterion("PARENT_ID =", value, "parentId");
            return (Criteria) this;
        }

        public Criteria andParentIdNotEqualTo(Integer value) {
            addCriterion("PARENT_ID <>", value, "parentId");
            return (Criteria) this;
        }

        public Criteria andParentIdGreaterThan(Integer value) {
            addCriterion("PARENT_ID >", value, "parentId");
            return (Criteria) this;
        }

        public Criteria andParentIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("PARENT_ID >=", value, "parentId");
            return (Criteria) this;
        }

        public Criteria andParentIdLessThan(Integer value) {
            addCriterion("PARENT_ID <", value, "parentId");
            return (Criteria) this;
        }

        public Criteria andParentIdLessThanOrEqualTo(Integer value) {
            addCriterion("PARENT_ID <=", value, "parentId");
            return (Criteria) this;
        }

        public Criteria andParentIdIn(List<Integer> values) {
            addCriterion("PARENT_ID in", values, "parentId");
            return (Criteria) this;
        }

        public Criteria andParentIdNotIn(List<Integer> values) {
            addCriterion("PARENT_ID not in", values, "parentId");
            return (Criteria) this;
        }

        public Criteria andParentIdBetween(Integer value1, Integer value2) {
            addCriterion("PARENT_ID between", value1, value2, "parentId");
            return (Criteria) this;
        }

        public Criteria andParentIdNotBetween(Integer value1, Integer value2) {
            addCriterion("PARENT_ID not between", value1, value2, "parentId");
            return (Criteria) this;
        }

        public Criteria andMenuCodeIsNull() {
            addCriterion("MENU_CODE is null");
            return (Criteria) this;
        }

        public Criteria andMenuCodeIsNotNull() {
            addCriterion("MENU_CODE is not null");
            return (Criteria) this;
        }

        public Criteria andMenuCodeEqualTo(String value) {
            addCriterion("MENU_CODE =", value, "menuCode");
            return (Criteria) this;
        }

        public Criteria andMenuCodeNotEqualTo(String value) {
            addCriterion("MENU_CODE <>", value, "menuCode");
            return (Criteria) this;
        }

        public Criteria andMenuCodeGreaterThan(String value) {
            addCriterion("MENU_CODE >", value, "menuCode");
            return (Criteria) this;
        }

        public Criteria andMenuCodeGreaterThanOrEqualTo(String value) {
            addCriterion("MENU_CODE >=", value, "menuCode");
            return (Criteria) this;
        }

        public Criteria andMenuCodeLessThan(String value) {
            addCriterion("MENU_CODE <", value, "menuCode");
            return (Criteria) this;
        }

        public Criteria andMenuCodeLessThanOrEqualTo(String value) {
            addCriterion("MENU_CODE <=", value, "menuCode");
            return (Criteria) this;
        }

        public Criteria andMenuCodeLike(String value) {
            addCriterion("MENU_CODE like", value, "menuCode");
            return (Criteria) this;
        }

        public Criteria andMenuCodeNotLike(String value) {
            addCriterion("MENU_CODE not like", value, "menuCode");
            return (Criteria) this;
        }

        public Criteria andMenuCodeIn(List<String> values) {
            addCriterion("MENU_CODE in", values, "menuCode");
            return (Criteria) this;
        }

        public Criteria andMenuCodeNotIn(List<String> values) {
            addCriterion("MENU_CODE not in", values, "menuCode");
            return (Criteria) this;
        }

        public Criteria andMenuCodeBetween(String value1, String value2) {
            addCriterion("MENU_CODE between", value1, value2, "menuCode");
            return (Criteria) this;
        }

        public Criteria andMenuCodeNotBetween(String value1, String value2) {
            addCriterion("MENU_CODE not between", value1, value2, "menuCode");
            return (Criteria) this;
        }

        public Criteria andMenuHrefIsNull() {
            addCriterion("MENU_HREF is null");
            return (Criteria) this;
        }

        public Criteria andMenuHrefIsNotNull() {
            addCriterion("MENU_HREF is not null");
            return (Criteria) this;
        }

        public Criteria andMenuHrefEqualTo(String value) {
            addCriterion("MENU_HREF =", value, "menuHref");
            return (Criteria) this;
        }

        public Criteria andMenuHrefNotEqualTo(String value) {
            addCriterion("MENU_HREF <>", value, "menuHref");
            return (Criteria) this;
        }

        public Criteria andMenuHrefGreaterThan(String value) {
            addCriterion("MENU_HREF >", value, "menuHref");
            return (Criteria) this;
        }

        public Criteria andMenuHrefGreaterThanOrEqualTo(String value) {
            addCriterion("MENU_HREF >=", value, "menuHref");
            return (Criteria) this;
        }

        public Criteria andMenuHrefLessThan(String value) {
            addCriterion("MENU_HREF <", value, "menuHref");
            return (Criteria) this;
        }

        public Criteria andMenuHrefLessThanOrEqualTo(String value) {
            addCriterion("MENU_HREF <=", value, "menuHref");
            return (Criteria) this;
        }

        public Criteria andMenuHrefLike(String value) {
            addCriterion("MENU_HREF like", value, "menuHref");
            return (Criteria) this;
        }

        public Criteria andMenuHrefNotLike(String value) {
            addCriterion("MENU_HREF not like", value, "menuHref");
            return (Criteria) this;
        }

        public Criteria andMenuHrefIn(List<String> values) {
            addCriterion("MENU_HREF in", values, "menuHref");
            return (Criteria) this;
        }

        public Criteria andMenuHrefNotIn(List<String> values) {
            addCriterion("MENU_HREF not in", values, "menuHref");
            return (Criteria) this;
        }

        public Criteria andMenuHrefBetween(String value1, String value2) {
            addCriterion("MENU_HREF between", value1, value2, "menuHref");
            return (Criteria) this;
        }

        public Criteria andMenuHrefNotBetween(String value1, String value2) {
            addCriterion("MENU_HREF not between", value1, value2, "menuHref");
            return (Criteria) this;
        }

        public Criteria andIsadminMenuIsNull() {
            addCriterion("ISADMIN_MENU is null");
            return (Criteria) this;
        }

        public Criteria andIsadminMenuIsNotNull() {
            addCriterion("ISADMIN_MENU is not null");
            return (Criteria) this;
        }

        public Criteria andIsadminMenuEqualTo(String value) {
            addCriterion("ISADMIN_MENU =", value, "isadminMenu");
            return (Criteria) this;
        }

        public Criteria andIsadminMenuNotEqualTo(String value) {
            addCriterion("ISADMIN_MENU <>", value, "isadminMenu");
            return (Criteria) this;
        }

        public Criteria andIsadminMenuGreaterThan(String value) {
            addCriterion("ISADMIN_MENU >", value, "isadminMenu");
            return (Criteria) this;
        }

        public Criteria andIsadminMenuGreaterThanOrEqualTo(String value) {
            addCriterion("ISADMIN_MENU >=", value, "isadminMenu");
            return (Criteria) this;
        }

        public Criteria andIsadminMenuLessThan(String value) {
            addCriterion("ISADMIN_MENU <", value, "isadminMenu");
            return (Criteria) this;
        }

        public Criteria andIsadminMenuLessThanOrEqualTo(String value) {
            addCriterion("ISADMIN_MENU <=", value, "isadminMenu");
            return (Criteria) this;
        }

        public Criteria andIsadminMenuLike(String value) {
            addCriterion("ISADMIN_MENU like", value, "isadminMenu");
            return (Criteria) this;
        }

        public Criteria andIsadminMenuNotLike(String value) {
            addCriterion("ISADMIN_MENU not like", value, "isadminMenu");
            return (Criteria) this;
        }

        public Criteria andIsadminMenuIn(List<String> values) {
            addCriterion("ISADMIN_MENU in", values, "isadminMenu");
            return (Criteria) this;
        }

        public Criteria andIsadminMenuNotIn(List<String> values) {
            addCriterion("ISADMIN_MENU not in", values, "isadminMenu");
            return (Criteria) this;
        }

        public Criteria andIsadminMenuBetween(String value1, String value2) {
            addCriterion("ISADMIN_MENU between", value1, value2, "isadminMenu");
            return (Criteria) this;
        }

        public Criteria andIsadminMenuNotBetween(String value1, String value2) {
            addCriterion("ISADMIN_MENU not between", value1, value2, "isadminMenu");
            return (Criteria) this;
        }

        public Criteria andIsDeleteIsNull() {
            addCriterion("IS_DELETE is null");
            return (Criteria) this;
        }

        public Criteria andIsDeleteIsNotNull() {
            addCriterion("IS_DELETE is not null");
            return (Criteria) this;
        }

        public Criteria andIsDeleteEqualTo(String value) {
            addCriterion("IS_DELETE =", value, "isDelete");
            return (Criteria) this;
        }

        public Criteria andIsDeleteNotEqualTo(String value) {
            addCriterion("IS_DELETE <>", value, "isDelete");
            return (Criteria) this;
        }

        public Criteria andIsDeleteGreaterThan(String value) {
            addCriterion("IS_DELETE >", value, "isDelete");
            return (Criteria) this;
        }

        public Criteria andIsDeleteGreaterThanOrEqualTo(String value) {
            addCriterion("IS_DELETE >=", value, "isDelete");
            return (Criteria) this;
        }

        public Criteria andIsDeleteLessThan(String value) {
            addCriterion("IS_DELETE <", value, "isDelete");
            return (Criteria) this;
        }

        public Criteria andIsDeleteLessThanOrEqualTo(String value) {
            addCriterion("IS_DELETE <=", value, "isDelete");
            return (Criteria) this;
        }

        public Criteria andIsDeleteLike(String value) {
            addCriterion("IS_DELETE like", value, "isDelete");
            return (Criteria) this;
        }

        public Criteria andIsDeleteNotLike(String value) {
            addCriterion("IS_DELETE not like", value, "isDelete");
            return (Criteria) this;
        }

        public Criteria andIsDeleteIn(List<String> values) {
            addCriterion("IS_DELETE in", values, "isDelete");
            return (Criteria) this;
        }

        public Criteria andIsDeleteNotIn(List<String> values) {
            addCriterion("IS_DELETE not in", values, "isDelete");
            return (Criteria) this;
        }

        public Criteria andIsDeleteBetween(String value1, String value2) {
            addCriterion("IS_DELETE between", value1, value2, "isDelete");
            return (Criteria) this;
        }

        public Criteria andIsDeleteNotBetween(String value1, String value2) {
            addCriterion("IS_DELETE not between", value1, value2, "isDelete");
            return (Criteria) this;
        }

        public Criteria andIscanUpdateIsNull() {
            addCriterion("ISCAN_UPDATE is null");
            return (Criteria) this;
        }

        public Criteria andIscanUpdateIsNotNull() {
            addCriterion("ISCAN_UPDATE is not null");
            return (Criteria) this;
        }

        public Criteria andIscanUpdateEqualTo(String value) {
            addCriterion("ISCAN_UPDATE =", value, "iscanUpdate");
            return (Criteria) this;
        }

        public Criteria andIscanUpdateNotEqualTo(String value) {
            addCriterion("ISCAN_UPDATE <>", value, "iscanUpdate");
            return (Criteria) this;
        }

        public Criteria andIscanUpdateGreaterThan(String value) {
            addCriterion("ISCAN_UPDATE >", value, "iscanUpdate");
            return (Criteria) this;
        }

        public Criteria andIscanUpdateGreaterThanOrEqualTo(String value) {
            addCriterion("ISCAN_UPDATE >=", value, "iscanUpdate");
            return (Criteria) this;
        }

        public Criteria andIscanUpdateLessThan(String value) {
            addCriterion("ISCAN_UPDATE <", value, "iscanUpdate");
            return (Criteria) this;
        }

        public Criteria andIscanUpdateLessThanOrEqualTo(String value) {
            addCriterion("ISCAN_UPDATE <=", value, "iscanUpdate");
            return (Criteria) this;
        }

        public Criteria andIscanUpdateLike(String value) {
            addCriterion("ISCAN_UPDATE like", value, "iscanUpdate");
            return (Criteria) this;
        }

        public Criteria andIscanUpdateNotLike(String value) {
            addCriterion("ISCAN_UPDATE not like", value, "iscanUpdate");
            return (Criteria) this;
        }

        public Criteria andIscanUpdateIn(List<String> values) {
            addCriterion("ISCAN_UPDATE in", values, "iscanUpdate");
            return (Criteria) this;
        }

        public Criteria andIscanUpdateNotIn(List<String> values) {
            addCriterion("ISCAN_UPDATE not in", values, "iscanUpdate");
            return (Criteria) this;
        }

        public Criteria andIscanUpdateBetween(String value1, String value2) {
            addCriterion("ISCAN_UPDATE between", value1, value2, "iscanUpdate");
            return (Criteria) this;
        }

        public Criteria andIscanUpdateNotBetween(String value1, String value2) {
            addCriterion("ISCAN_UPDATE not between", value1, value2, "iscanUpdate");
            return (Criteria) this;
        }

        public Criteria andMenuLevelIsNull() {
            addCriterion("MENU_LEVEL is null");
            return (Criteria) this;
        }

        public Criteria andMenuLevelIsNotNull() {
            addCriterion("MENU_LEVEL is not null");
            return (Criteria) this;
        }

        public Criteria andMenuLevelEqualTo(String value) {
            addCriterion("MENU_LEVEL =", value, "menuLevel");
            return (Criteria) this;
        }

        public Criteria andMenuLevelNotEqualTo(String value) {
            addCriterion("MENU_LEVEL <>", value, "menuLevel");
            return (Criteria) this;
        }

        public Criteria andMenuLevelGreaterThan(String value) {
            addCriterion("MENU_LEVEL >", value, "menuLevel");
            return (Criteria) this;
        }

        public Criteria andMenuLevelGreaterThanOrEqualTo(String value) {
            addCriterion("MENU_LEVEL >=", value, "menuLevel");
            return (Criteria) this;
        }

        public Criteria andMenuLevelLessThan(String value) {
            addCriterion("MENU_LEVEL <", value, "menuLevel");
            return (Criteria) this;
        }

        public Criteria andMenuLevelLessThanOrEqualTo(String value) {
            addCriterion("MENU_LEVEL <=", value, "menuLevel");
            return (Criteria) this;
        }

        public Criteria andMenuLevelLike(String value) {
            addCriterion("MENU_LEVEL like", value, "menuLevel");
            return (Criteria) this;
        }

        public Criteria andMenuLevelNotLike(String value) {
            addCriterion("MENU_LEVEL not like", value, "menuLevel");
            return (Criteria) this;
        }

        public Criteria andMenuLevelIn(List<String> values) {
            addCriterion("MENU_LEVEL in", values, "menuLevel");
            return (Criteria) this;
        }

        public Criteria andMenuLevelNotIn(List<String> values) {
            addCriterion("MENU_LEVEL not in", values, "menuLevel");
            return (Criteria) this;
        }

        public Criteria andMenuLevelBetween(String value1, String value2) {
            addCriterion("MENU_LEVEL between", value1, value2, "menuLevel");
            return (Criteria) this;
        }

        public Criteria andMenuLevelNotBetween(String value1, String value2) {
            addCriterion("MENU_LEVEL not between", value1, value2, "menuLevel");
            return (Criteria) this;
        }

        public Criteria andButtonHtmlcontentIsNull() {
            addCriterion("BUTTON_HTMLCONTENT is null");
            return (Criteria) this;
        }

        public Criteria andButtonHtmlcontentIsNotNull() {
            addCriterion("BUTTON_HTMLCONTENT is not null");
            return (Criteria) this;
        }

        public Criteria andButtonHtmlcontentEqualTo(String value) {
            addCriterion("BUTTON_HTMLCONTENT =", value, "buttonHtmlcontent");
            return (Criteria) this;
        }

        public Criteria andButtonHtmlcontentNotEqualTo(String value) {
            addCriterion("BUTTON_HTMLCONTENT <>", value, "buttonHtmlcontent");
            return (Criteria) this;
        }

        public Criteria andButtonHtmlcontentGreaterThan(String value) {
            addCriterion("BUTTON_HTMLCONTENT >", value, "buttonHtmlcontent");
            return (Criteria) this;
        }

        public Criteria andButtonHtmlcontentGreaterThanOrEqualTo(String value) {
            addCriterion("BUTTON_HTMLCONTENT >=", value, "buttonHtmlcontent");
            return (Criteria) this;
        }

        public Criteria andButtonHtmlcontentLessThan(String value) {
            addCriterion("BUTTON_HTMLCONTENT <", value, "buttonHtmlcontent");
            return (Criteria) this;
        }

        public Criteria andButtonHtmlcontentLessThanOrEqualTo(String value) {
            addCriterion("BUTTON_HTMLCONTENT <=", value, "buttonHtmlcontent");
            return (Criteria) this;
        }

        public Criteria andButtonHtmlcontentLike(String value) {
            addCriterion("BUTTON_HTMLCONTENT like", value, "buttonHtmlcontent");
            return (Criteria) this;
        }

        public Criteria andButtonHtmlcontentNotLike(String value) {
            addCriterion("BUTTON_HTMLCONTENT not like", value, "buttonHtmlcontent");
            return (Criteria) this;
        }

        public Criteria andButtonHtmlcontentIn(List<String> values) {
            addCriterion("BUTTON_HTMLCONTENT in", values, "buttonHtmlcontent");
            return (Criteria) this;
        }

        public Criteria andButtonHtmlcontentNotIn(List<String> values) {
            addCriterion("BUTTON_HTMLCONTENT not in", values, "buttonHtmlcontent");
            return (Criteria) this;
        }

        public Criteria andButtonHtmlcontentBetween(String value1, String value2) {
            addCriterion("BUTTON_HTMLCONTENT between", value1, value2, "buttonHtmlcontent");
            return (Criteria) this;
        }

        public Criteria andButtonHtmlcontentNotBetween(String value1, String value2) {
            addCriterion("BUTTON_HTMLCONTENT not between", value1, value2, "buttonHtmlcontent");
            return (Criteria) this;
        }

        public Criteria andIsmenuIsNull() {
            addCriterion("ISMENU is null");
            return (Criteria) this;
        }

        public Criteria andIsmenuIsNotNull() {
            addCriterion("ISMENU is not null");
            return (Criteria) this;
        }

        public Criteria andIsmenuEqualTo(String value) {
            addCriterion("ISMENU =", value, "ismenu");
            return (Criteria) this;
        }

        public Criteria andIsmenuNotEqualTo(String value) {
            addCriterion("ISMENU <>", value, "ismenu");
            return (Criteria) this;
        }

        public Criteria andIsmenuGreaterThan(String value) {
            addCriterion("ISMENU >", value, "ismenu");
            return (Criteria) this;
        }

        public Criteria andIsmenuGreaterThanOrEqualTo(String value) {
            addCriterion("ISMENU >=", value, "ismenu");
            return (Criteria) this;
        }

        public Criteria andIsmenuLessThan(String value) {
            addCriterion("ISMENU <", value, "ismenu");
            return (Criteria) this;
        }

        public Criteria andIsmenuLessThanOrEqualTo(String value) {
            addCriterion("ISMENU <=", value, "ismenu");
            return (Criteria) this;
        }

        public Criteria andIsmenuLike(String value) {
            addCriterion("ISMENU like", value, "ismenu");
            return (Criteria) this;
        }

        public Criteria andIsmenuNotLike(String value) {
            addCriterion("ISMENU not like", value, "ismenu");
            return (Criteria) this;
        }

        public Criteria andIsmenuIn(List<String> values) {
            addCriterion("ISMENU in", values, "ismenu");
            return (Criteria) this;
        }

        public Criteria andIsmenuNotIn(List<String> values) {
            addCriterion("ISMENU not in", values, "ismenu");
            return (Criteria) this;
        }

        public Criteria andIsmenuBetween(String value1, String value2) {
            addCriterion("ISMENU between", value1, value2, "ismenu");
            return (Criteria) this;
        }

        public Criteria andIsmenuNotBetween(String value1, String value2) {
            addCriterion("ISMENU not between", value1, value2, "ismenu");
            return (Criteria) this;
        }

        public Criteria andMenuParm1IsNull() {
            addCriterion("MENU_PARM1 is null");
            return (Criteria) this;
        }

        public Criteria andMenuParm1IsNotNull() {
            addCriterion("MENU_PARM1 is not null");
            return (Criteria) this;
        }

        public Criteria andMenuParm1EqualTo(Integer value) {
            addCriterion("MENU_PARM1 =", value, "menuParm1");
            return (Criteria) this;
        }

        public Criteria andMenuParm1NotEqualTo(Integer value) {
            addCriterion("MENU_PARM1 <>", value, "menuParm1");
            return (Criteria) this;
        }

        public Criteria andMenuParm1GreaterThan(Integer value) {
            addCriterion("MENU_PARM1 >", value, "menuParm1");
            return (Criteria) this;
        }

        public Criteria andMenuParm1GreaterThanOrEqualTo(Integer value) {
            addCriterion("MENU_PARM1 >=", value, "menuParm1");
            return (Criteria) this;
        }

        public Criteria andMenuParm1LessThan(Integer value) {
            addCriterion("MENU_PARM1 <", value, "menuParm1");
            return (Criteria) this;
        }

        public Criteria andMenuParm1LessThanOrEqualTo(Integer value) {
            addCriterion("MENU_PARM1 <=", value, "menuParm1");
            return (Criteria) this;
        }

        public Criteria andMenuParm1In(List<Integer> values) {
            addCriterion("MENU_PARM1 in", values, "menuParm1");
            return (Criteria) this;
        }

        public Criteria andMenuParm1NotIn(List<Integer> values) {
            addCriterion("MENU_PARM1 not in", values, "menuParm1");
            return (Criteria) this;
        }

        public Criteria andMenuParm1Between(Integer value1, Integer value2) {
            addCriterion("MENU_PARM1 between", value1, value2, "menuParm1");
            return (Criteria) this;
        }

        public Criteria andMenuParm1NotBetween(Integer value1, Integer value2) {
            addCriterion("MENU_PARM1 not between", value1, value2, "menuParm1");
            return (Criteria) this;
        }

        public Criteria andMenuParm2IsNull() {
            addCriterion("MENU_PARM2 is null");
            return (Criteria) this;
        }

        public Criteria andMenuParm2IsNotNull() {
            addCriterion("MENU_PARM2 is not null");
            return (Criteria) this;
        }

        public Criteria andMenuParm2EqualTo(Integer value) {
            addCriterion("MENU_PARM2 =", value, "menuParm2");
            return (Criteria) this;
        }

        public Criteria andMenuParm2NotEqualTo(Integer value) {
            addCriterion("MENU_PARM2 <>", value, "menuParm2");
            return (Criteria) this;
        }

        public Criteria andMenuParm2GreaterThan(Integer value) {
            addCriterion("MENU_PARM2 >", value, "menuParm2");
            return (Criteria) this;
        }

        public Criteria andMenuParm2GreaterThanOrEqualTo(Integer value) {
            addCriterion("MENU_PARM2 >=", value, "menuParm2");
            return (Criteria) this;
        }

        public Criteria andMenuParm2LessThan(Integer value) {
            addCriterion("MENU_PARM2 <", value, "menuParm2");
            return (Criteria) this;
        }

        public Criteria andMenuParm2LessThanOrEqualTo(Integer value) {
            addCriterion("MENU_PARM2 <=", value, "menuParm2");
            return (Criteria) this;
        }

        public Criteria andMenuParm2In(List<Integer> values) {
            addCriterion("MENU_PARM2 in", values, "menuParm2");
            return (Criteria) this;
        }

        public Criteria andMenuParm2NotIn(List<Integer> values) {
            addCriterion("MENU_PARM2 not in", values, "menuParm2");
            return (Criteria) this;
        }

        public Criteria andMenuParm2Between(Integer value1, Integer value2) {
            addCriterion("MENU_PARM2 between", value1, value2, "menuParm2");
            return (Criteria) this;
        }

        public Criteria andMenuParm2NotBetween(Integer value1, Integer value2) {
            addCriterion("MENU_PARM2 not between", value1, value2, "menuParm2");
            return (Criteria) this;
        }

        public Criteria andMenuParm3IsNull() {
            addCriterion("MENU_PARM3 is null");
            return (Criteria) this;
        }

        public Criteria andMenuParm3IsNotNull() {
            addCriterion("MENU_PARM3 is not null");
            return (Criteria) this;
        }

        public Criteria andMenuParm3EqualTo(String value) {
            addCriterion("MENU_PARM3 =", value, "menuParm3");
            return (Criteria) this;
        }

        public Criteria andMenuParm3NotEqualTo(String value) {
            addCriterion("MENU_PARM3 <>", value, "menuParm3");
            return (Criteria) this;
        }

        public Criteria andMenuParm3GreaterThan(String value) {
            addCriterion("MENU_PARM3 >", value, "menuParm3");
            return (Criteria) this;
        }

        public Criteria andMenuParm3GreaterThanOrEqualTo(String value) {
            addCriterion("MENU_PARM3 >=", value, "menuParm3");
            return (Criteria) this;
        }

        public Criteria andMenuParm3LessThan(String value) {
            addCriterion("MENU_PARM3 <", value, "menuParm3");
            return (Criteria) this;
        }

        public Criteria andMenuParm3LessThanOrEqualTo(String value) {
            addCriterion("MENU_PARM3 <=", value, "menuParm3");
            return (Criteria) this;
        }

        public Criteria andMenuParm3Like(String value) {
            addCriterion("MENU_PARM3 like", value, "menuParm3");
            return (Criteria) this;
        }

        public Criteria andMenuParm3NotLike(String value) {
            addCriterion("MENU_PARM3 not like", value, "menuParm3");
            return (Criteria) this;
        }

        public Criteria andMenuParm3In(List<String> values) {
            addCriterion("MENU_PARM3 in", values, "menuParm3");
            return (Criteria) this;
        }

        public Criteria andMenuParm3NotIn(List<String> values) {
            addCriterion("MENU_PARM3 not in", values, "menuParm3");
            return (Criteria) this;
        }

        public Criteria andMenuParm3Between(String value1, String value2) {
            addCriterion("MENU_PARM3 between", value1, value2, "menuParm3");
            return (Criteria) this;
        }

        public Criteria andMenuParm3NotBetween(String value1, String value2) {
            addCriterion("MENU_PARM3 not between", value1, value2, "menuParm3");
            return (Criteria) this;
        }

        public Criteria andMenuParm4IsNull() {
            addCriterion("MENU_PARM4 is null");
            return (Criteria) this;
        }

        public Criteria andMenuParm4IsNotNull() {
            addCriterion("MENU_PARM4 is not null");
            return (Criteria) this;
        }

        public Criteria andMenuParm4EqualTo(String value) {
            addCriterion("MENU_PARM4 =", value, "menuParm4");
            return (Criteria) this;
        }

        public Criteria andMenuParm4NotEqualTo(String value) {
            addCriterion("MENU_PARM4 <>", value, "menuParm4");
            return (Criteria) this;
        }

        public Criteria andMenuParm4GreaterThan(String value) {
            addCriterion("MENU_PARM4 >", value, "menuParm4");
            return (Criteria) this;
        }

        public Criteria andMenuParm4GreaterThanOrEqualTo(String value) {
            addCriterion("MENU_PARM4 >=", value, "menuParm4");
            return (Criteria) this;
        }

        public Criteria andMenuParm4LessThan(String value) {
            addCriterion("MENU_PARM4 <", value, "menuParm4");
            return (Criteria) this;
        }

        public Criteria andMenuParm4LessThanOrEqualTo(String value) {
            addCriterion("MENU_PARM4 <=", value, "menuParm4");
            return (Criteria) this;
        }

        public Criteria andMenuParm4Like(String value) {
            addCriterion("MENU_PARM4 like", value, "menuParm4");
            return (Criteria) this;
        }

        public Criteria andMenuParm4NotLike(String value) {
            addCriterion("MENU_PARM4 not like", value, "menuParm4");
            return (Criteria) this;
        }

        public Criteria andMenuParm4In(List<String> values) {
            addCriterion("MENU_PARM4 in", values, "menuParm4");
            return (Criteria) this;
        }

        public Criteria andMenuParm4NotIn(List<String> values) {
            addCriterion("MENU_PARM4 not in", values, "menuParm4");
            return (Criteria) this;
        }

        public Criteria andMenuParm4Between(String value1, String value2) {
            addCriterion("MENU_PARM4 between", value1, value2, "menuParm4");
            return (Criteria) this;
        }

        public Criteria andMenuParm4NotBetween(String value1, String value2) {
            addCriterion("MENU_PARM4 not between", value1, value2, "menuParm4");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table CONSOLE_MENU
     *
     * @mbggenerated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table CONSOLE_MENU
     *
     * @mbggenerated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value) {
            super();
            this.condition = condition;
            this.value = value;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.betweenValue = true;
        }
    }
}